cdimmunity/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *


urlpatterns = [
    path('', index, name='index'),
    path('signup/', signup, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('home/', home, name='home'),
    path('remind/', remind, name='remind'),
    path('rm_suc/', rm_suc, name='rm_suc'),
    path('cldreg/', cldreg, name='cldreg'),
    path('event_reminder/', event_reminder, name='event_reminder'),
    path('reminder-settings-updated/', reminder_settings_updated, name='reminder_settings_updated'),
    path('email_sent_confirmation/', email_sent_confirmation, name='email_sent_confirmation'),
    path('cldreg_success/', cldreg_success, name='cldreg_success'),
    path('immunization_schedule/', immunization_schedule, name='immunization_schedule'),
    path('view_schedule/', view_schedule, name='view_schedule'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name='password_reset_complete'),
]

childimmune/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cdimmunity.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cdimmunity/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError(_('The Email field must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        
        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))

        return self.create_user(email, username, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(_('username'), max_length=150, unique=True)
    profile_picture = models.ImageField(_('profile picture'), upload_to='profile_pics/', blank=True, null=True)  # New field
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin site.'))
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

#family table
class Family(models.Model):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    address_line1 = models.CharField(max_length=100, blank=True, null=True)
    address_line2 = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    occupation = models.CharField(max_length=100, blank=True, null=True)
    relationship = models.CharField(max_length=100, blank=True, null=True)
    preferred_language = models.CharField(max_length=100, blank=True, null=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    # Child fields
    child_name = models.CharField(max_length=100)
    child_date_of_birth = models.DateField()
    child_gender = models.CharField(max_length=10)  # Remove choices argument
    child_place_of_birth = models.CharField(max_length=100)
    child_blood_type = models.CharField(max_length=5)  # Remove choices argument

    def __str__(self):
        return self.email
    
class ImmunizationSchedule(models.Model):
    vaccine_name = models.CharField(max_length=100)
    recommended_age = models.PositiveIntegerField(help_text="Recommended age in months for this dose")
    number_of_doses = models.PositiveIntegerField(default=1)
    additional_info = models.TextField(blank=True, null=True)
    child_name = models.CharField(max_length=100)
    child_image = models.ImageField(upload_to='child_images/', blank=True, null=True)

    def __str__(self):
        return self.vaccine_name
    
#Reminder settings model
from django.conf import settings

class ReminderSettings(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    email_reminder = models.BooleanField(default=False)
    sms_reminder = models.BooleanField(default=False)
    event_date = models.DateField(null=True, blank=True)  # New field for event date

    def __str__(self):
        return f"Reminder Settings for {self.user.username}"

cdimmunity/views.py
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .forms import *
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth import authenticate, login
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.urls import reverse
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib import messages
from django.contrib.auth.models import User


#RESET PASS1
def send_password_reset_email(request, email):
    # Check if the email exists in the database
    try:
        user = User.objects.get(email=email)
    except User.DoesNotExist:
        # Handle the case where the email does not exist
        messages.error(request, 'User with this email does not exist.')
        return None

    # Generate a password reset token
    token = default_token_generator.make_token(user)

    # Encode the user's ID and token to be included in the URL
    uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
    token = default_token_generator.make_token(user)

    # Construct the password reset URL
    reset_url = request.build_absolute_uri(reverse('password_reset_confirm', kwargs={'uidb64': uidb64, 'token': token}))

    # Render the email template with the reset URL
    email_subject = 'Password Reset'
    email_body = render_to_string('password_reset_email.html', {'reset_url': reset_url})

    # Send the email
    send_mail(email_subject, email_body, 'enote7y@gmail.com', [email])

#SIGNINUP
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            # Process form submission
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            if 'profile_picture' in request.FILES:
                user.profile_picture = request.FILES['profile_picture']
            user.save()
            return redirect('login')  # Redirect to login page after signup
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})
        

#LOGIN USER
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)  # Correct usage of login() function
                # Redirect to the page user was trying to access, or home page if no next parameter
                next_page = request.GET.get('next', 'home')
                return redirect(next_page)
            else:
                form.add_error(None, 'Invalid email or password. Please try again.')
    else:
        form = LoginForm()

    # If the next parameter exists, pass it to the template to display a message
    next_param = request.GET.get('next')
    return render(request, 'login.html', {'form': form, 'next_param': next_param})

@login_required
def home(request):
    # Filter Family objects based on the currently logged-in user
    families = Family.objects.filter(email=request.user.email)
    return render(request, 'home.html', {'families': families})

def index (request):
    return render(request, 'index.html')

@login_required
def cldreg_success (request):
    return render(request, 'cldreg_success.html')

@login_required
def rm_suc (request):
    return render(request, 'rm_suc.html')

#child register
from .forms import FamilyForm

@login_required
def cldreg(request):
    if request.method == 'POST':
        form = FamilyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cldreg_success')  # Redirect to success page
    else:
        form = FamilyForm()
    return render(request, 'cldreg.html', {'form': form})

#immunization schedule
@login_required
def immunization_schedule(request):
    if request.method == 'POST':
        form = ImmunizationScheduleForm(request.POST, request.FILES)  # Include request.FILES to handle file uploads
        if form.is_valid():
            # Save the form instance without committing to the database yet
            schedule = form.save(commit=False)
            # Manually set the child image field with the uploaded file
            schedule.child_image = request.FILES.get('child_image')
            # Save the form instance to the database
            schedule.save()
            # Redirect to a success page or wherever appropriate
            return redirect('view_schedule')
    else:
        form = ImmunizationScheduleForm()
    return render(request, 'immunization_schedule.html', {'form': form})


@login_required
def view_schedule(request):
    query = request.GET.get('search')
    if query:
        immunization_schedule = ImmunizationSchedule.objects.filter(
            Q(child_name__icontains=query) |
            Q(vaccine_name__icontains=query)
        )
    else:
        immunization_schedule = ImmunizationSchedule.objects.all()

    return render(request, 'view_schedule.html', {'immunization_schedule': immunization_schedule})

#Logout
from django.contrib.auth import logout

def logout_view(request):
    logout(request)
    return redirect('index')  

#Reminder settings
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse
from django.utils.timezone import now
# Add necessary imports
from django.http import HttpResponseNotAllowed, HttpResponseServerError
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required
def remind(request):
    # Retrieve or create reminder settings for the current user
    reminder_settings, created = ReminderSettings.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        form = ReminderSettingsForm(request.POST, instance=reminder_settings)
        if form.is_valid():
            # Save the updated reminder settings
            form.save()

            # Check if email reminder is enabled
            if reminder_settings.email_reminder:
                try:
                    # Prepare email content
                    subject = 'Reminder Settings Updated'
                    current_site = get_current_site(request)
                    context = {
                        'user': request.user,
                        'domain': current_site.domain,
                        'settings_url': reverse('remind'),  # Assuming this is the URL to the reminder settings page
                    }
                    html_message = render_to_string('reminder_settings_updated.html', context)
                    plain_message = strip_tags(html_message)

                    # Send email notification
                    send_mail(
                        subject,
                        plain_message,
                        'enote7y@gmail.com',  # Replace with your email sender
                        [request.user.email],  # Send email to the user
                        html_message=html_message,
                    )
                except Exception as e:
                    # Log or print the exception for debugging
                    print(f"Error sending email: {e}")
                    messages.error(request, 'Error sending email notification.')
                    
            # Check if the event date is today
            event_date = form.cleaned_data.get('event_date')
            if event_date == now().date():
                try:
                    # Send email notification for event reminder
                    send_event_reminder_email(request.user.email, event_date)
                except Exception as e:
                    # Log or print the exception for debugging
                    print(f"Error sending event reminder email: {e}")
                    messages.error(request, 'Error sending event reminder email.')
                    
            # Redirect to a success page or wherever appropriate
            return redirect('rm_suc')  # Update with the appropriate URL name
    else:
        form = ReminderSettingsForm(instance=reminder_settings)

    return render(request, 'remind.html', {'form': form})


@login_required
def send_event_reminder_email(recipient_email, event_date):
    subject = 'Event Reminder'
    message = render_to_string('event_reminder.html', {'event_date': event_date})
    sender_email = 'enote7y@gmail.com'  # Update with your sender email
    send_mail(subject, message, sender_email, [recipient_email])


#notifying
from django.conf import settings
from django.template.loader import render_to_string

@login_required
def reminder_settings_updated(request):
    # Retrieve the user and their updated reminder settings
    user = request.user
    reminder_settings = user.remindersettings

    # Render the email content template with appropriate context
    email_subject = 'Reminder Settings Updated'

    # Include the event date in the email template context
    event_date = reminder_settings.event_date.strftime('%Y-%m-%d') if reminder_settings.event_date else None

    email_body = render_to_string('reminder_settings_updated.html', {
        'user': user,
        'domain': settings.DOMAIN,  # Your website domain
        'settings_url': 'URL to view the reminder settings',  # Update with the actual URL
        'event_date': event_date,  # Pass the event date to the template context
    })

    # Send the email
    send_mail(

cdimmunity/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>{% block title %}Your Website{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body class="light-mode" style="background-image: url('https://wallpaperaccess.com/full/2348994.jpg'); background-size: cover; background-repeat: no-repeat;">
    <header>
        <nav style="background-color: #0e0205;">
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'remind' %}">Update Reminder Settings</a></li>
                <li><a href="{% url 'view_schedule' %}">See the Immunisation Schedule</a></li>
                <li><a href="{% url 'immunization_schedule' %}">Fill in the Immunization Schedule</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'signup' %}">Sign Up</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </nav>
        <!-- Theme switcher -->
        <div id="theme-switcher" onclick="toggleTheme()">
            🌙<em>Theme</em>
        </div>
    </header>

    <div class="container">
        <!-- Content -->
        {% block content %}

        <script>
            window.onload = function() {
                alert("Lost ID report posted successfully!");  // Show pop-up message
            }
        </script>

        {% endblock %}

    </div>
    <script>
        // Function to toggle between dark and light themes
        function toggleTheme() {
            var body = document.body;
            body.classList.toggle("dark-mode");
            body.classList.toggle("light-mode");

            // Store the theme preference in local storage
            var isDarkMode = body.classList.contains("dark-mode");
            localStorage.setItem("theme", isDarkMode ? "dark" : "light");
        }

        // Check if the user has a theme preference stored in local storage
        var storedTheme = localStorage.getItem("theme");
        if (storedTheme === "dark") {
            toggleTheme(); // Apply dark theme if it was previously selected
        }
    </script>
</body>
</html>

cdimmunity/templates/cldreg.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <title>Parent and Child Registration</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style2.css' %}"
    />
  </head>
  <body class="light-mode" style="background-image: url('https://wallpaperaccess.com/full/2348995.jpg'); background-size: cover; ">
    <div class="content-container">
      <h1 style="color: blue;">Parent and Child Registration</h1>
      <h2 style="color: rgb(175, 160, 160);">
        <em
          >date format eg
          <span style="size: 1cqb; color: rgb(236, 14, 81)">"1990-12-09"</span></em
        >
      </h2>
      <h1>
        <em
          ><span style="color: rgb(243, 227, 10)"
            >"and you cannot use an existing email choose your own email or
            another email"</span
          ></em
        >
      </h1>
      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Register</button>
      </form>
      <br />
      <div style="text-align: center">
        <form action="{% url 'home' %}" method="get">
          <button type="submit" class="btn btn-primary">
            Cancel this registration
          </button>
        </form>
      </div>
    </div>
  </body>
</html>

cdimmunity/templates/email_sent_confirmation.html
{% extends 'base.html' %}

{% block title %}
    Email Sent Confirmation
{% endblock %}

{% block content %}
    <h1>Email Sent</h1>
    <p>An email with the updated reminder settings has been sent to your email address.</p>
{% endblock %}

cdimmunity/templates/event_reminder.html
    YOUR CHILD IMMUNIZATION Reminder, {{username}}

    This is a reminder for the upcoming event on {{ event_date }}.
    Please make sure to attend or complete any necessary preparations.
    Thank you!

cdimmunity/templates/immunization_schedule.html
{% extends 'base.html' %} {% block title %} Immunization Schedule {% endblock %}
{% block content %}
<div
  style="
    background-image: linear-gradient(to bottom, #87cefa, #add8e6);
    background-size: cover;
    background-position: center;
    padding: 20px;
  "
>
  <h1 style="text-align: center; color: #fff">Immunization Schedule</h1>
  <form
    method="post"
    enctype="multipart/form-data"
    style="
      background-color: rgba(0, 123, 255, 0.5);
      padding: 20px;
      border-radius: 10px;
      text-align: center;
    "
  >
    {% csrf_token %}
    <div style="margin-bottom: 10px">
      {{ form.vaccine_name.label_tag }}<br />
      {{ form.vaccine_name }}
    </div>
    <div style="margin-bottom: 10px">
      {{ form.recommended_age.label_tag }}<br />
      {{ form.recommended_age }}
    </div>
    <div style="margin-bottom: 10px">
      {{ form.number_of_doses.label_tag }}<br />
      {{ form.number_of_doses }}
    </div>
    <div style="margin-bottom: 10px">
      {{ form.additional_info.label_tag }}<br />
      {{ form.additional_info }}
    </div>
    <div style="margin-bottom: 10px">
      {{ form.child_name.label_tag }}<br />
      {{ form.child_name }}
    </div>
    <div style="margin-bottom: 10px">
      {{ form.child_image.label_tag }}<br />
      {{ form.child_image }}
    </div>
    <button
      type="submit"
      style="
        background-color: #3b5998;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
      "
    >
      Submit
    </button>
  </form>
  <br />
  <div style="text-align: center">
    <form method="post" action="{% url 'logout' %}">
      {% csrf_token %}
      <button
        type="submit"
        class="btn btn-primary"
        style="
          background-color: #3b5998;
          color: #fff;
          border: none;
          padding: 10px 20px;
          border-radius: 5px;
          cursor: pointer;
        "
      >
        Logout
      </button>
    </form>
    <br />
    <form method="post" action="{% url 'home' %}">
      {% csrf_token %}
      <button
        type="submit"
        class="btn btn-primary"
        style="
          background-color: #3b5998;
          color: #fff;
          border: none;
          padding: 10px 20px;
          border-radius: 5px;
          cursor: pointer;
        "
      >
        Cancel
      </button>
    </form>
  </div>
</div>
{% endblock %}

cdimmunity/templates/index.html
{% extends 'base.html' %} {% block title %} Your Page Title {% endblock %} 
{% block content %}

<div class="form-container"
     style="
      background-color: rgba(0, 123, 255, 0.5);
      padding: 20px;
      border-radius: 10px;
      text-align: center;
      "
  >
  <h2 style="background-color: yellowgreen;">Welcome to  CHILD IMMUNIZATION TRACKING SYSTEM</h2>
  <br />
  <h3 style="color: rgb(29, 58, 59);">Get ready to Keep your child safe with easy record keeping</h3>
  <br />
  <form
    action="{% url 'signup' %}"
    method="get"
    style="
      background-color: rgba(22, 21, 21, 0.8);
      padding: 20px;
      border-radius: 10px;
    "
  >
    <button
      type="submit"
      style="
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
      "
    >
      Create Account
    </button>
  </form>
  <br />
  <form
    action="{% url 'login' %}"
    method="get"
    style="
      background-color: rgba(22, 21, 21, 0.8);
      padding: 20px;
      border-radius: 10px;
    "
  >
    <button
      type="submit"
      style="
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
      "
    >
      Already have an account
    </button>
  </form><br>
  <form
    action="{% url 'login' %}"
    method="get"
    style="
      background-color: rgba(22, 21, 21, 0.8);
      padding: 20px;
      border-radius: 10px;
    "
  >
    <button
      type="submit"
      style="
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
      "
    >
      <a href="http://127.0.0.1:8000/admin/">Admin Access?</a>
    </button>
  </form>
</div>
{% endblock %}

cdimmunity/templates/login.html
{% extends 'base.html' %} {% block title %} Login - My Website {% endblock %} {% block content %}
<div class="form-container">
  <h2>Login</h2>
  {% if request.GET.next %}
  <p>Please log in to access <strong>{{ request.GET.next }}</strong>.</p>
  {% endif %} {% if form.non_field_errors %}
  <div class="alert alert-danger">{{ form.non_field_errors }}</div>
  {% endif %}
  <form
    method="post"
    style="
      background-color: rgba(0, 123, 255, 0.5);
      padding: 20px;
      border-radius: 10px;
      text-align: center;
    "
  >
    {% csrf_token %}
    <div style="margin-bottom: 10px">
      {{ form.email.label_tag }}<br />
      {{ form.email }}
    </div>
    <div style="margin-bottom: 10px">
      {{ form.password.label_tag }}<br />
      {{ form.password }}
    </div>
    <button
      type="submit"
      style="
        background-color: #fff;
        color: #007bff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
      "
    >
      Login
    </button>
  </form>
  <br />
  <form action="{% url 'signup' %}" method="get">
    <button
      type="submit"
      style="
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
      "
    >
      Don't have an account yet 😔
    </button>
  </form>
  <br />
  <form action="{% url 'password_reset' %}" method="get">
    <button
      type="submit"
      style="
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
      "
    >
      Forgot Password?
    </button>
  </form>
</div>
{% endblock %}

cdimmunity/templates/password_reset.html
{% extends 'base.html' %}

{% block title %}Login - My Website{% endblock %}

{% block content %}
<h1>     Forgotten your password 😒? </h1>
    <p>Please reset here....<br>
    <H2> Enter your email address below, and we'll email instructions <br>
     for setting a new one. </H2></p>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit"/>
</form>
     
{% endblock %}

cdimmunity/templates/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Login - My Website{% endblock %}

{% block content %}
<h1>Password reset complete 👍</h1>
<h2>Your password has been set. You may go ahead and log in now.</h2><br>
<form action="{% url 'login' %}" method="get">
    <button type="submit" class="btn btn-primary">LOGIN NOW <br>😁</button>
  </form>
     
{% endblock %}

cdimmunity/templates/password_reset_email.html
{% extends 'base.html' %}

{% block title %}Password Reset{% endblock %}

{% block content %}
    <p>To reset your password, please click the link below:</p>
    <p><a href="{{ reset_url }}">Reset Password</a></p>
{% endblock %}

cdimmunity/templates/remind.html
{% extends 'base.html' %}

{% block title %}
    Reminder Settings
{% endblock %}

{% block content %}
    <div style="background-image: linear-gradient(to bottom, #87CEFA, #ADD8E6); padding: 20px; border-radius: 10px;">
        <h1 style="text-align: center; color: #fff;">Reminder Settings</h1>
        
        <!-- Reminder Settings Form -->
        <form method="post" style="background-color: rgba(0, 123, 255, 0.5); padding: 20px; border-radius: 10px; text-align: center;">
            {% csrf_token %}
            {{ form.email_reminder.label_tag }}<br>
            {{ form.email_reminder }}<br><br>
            {{ form.sms_reminder.label_tag }}<br>
            {{ form.sms_reminder }}<br><br>
            <label for="id_event_date" style="color: #fff;">Event Date:</label>
            <input type="date" id="id_event_date" name="event_date" value="{{ form.instance.event_date|date:'Y-m-d' }}" style="padding: 5px; border-radius: 5px; margin-bottom: 10px;"><br>
            <button type="submit" style="background-color: #3b5998; color: #fff; padding: 10px 20px; border: none; border-radius: 5px;">Update</button>
        </form>

        <br>
        <form method="get" action="{% url 'home' %}">
            <button type="submit" class="btn btn-primary" style="background-color: #3b5998; color: #fff; padding: 10px 20px; border: none; border-radius: 5px;">Back to Dashboard</button>
        </form>
    </div>
{% endblock %}

cdimmunity/templates/reminder_settings_updated.html
{% extends 'base.html' %}

{% block title %}
    Reminder Settings Updated
{% endblock %}

{% block content %}
    <p>Dear {{ user.username }},</p>
    
    <p>Your reminder settings have been successfully updated.</p>
    
    <!-- Display event date -->
    {% if event_date %}
    <p>Event Date: {{ event_date }}</p>
    {% endif %}
    
    <p>You can review your settings by visiting the following link:</p>
    <p><a href="http://127.0.0.1:8000/remind/">{{ settings_url }}</a></p>
    
    <p>Thank you for using our service.</p>
    
    <p>Sincerely,<br>
        Heath cures.</p>
{% endblock %}

cdimmunity/templates/reset.html
{% extends 'base.html' %}

{% block title %}Login - My Website{% endblock %}

{% block content %}
<h1>Enter new password 👇</h1><br>
    <H2>Please enter your new password twice so we can verify you typed it in correctly.🙏😌!</H2>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit"/>
</form>
     
{% endblock %}

cdimmunity/templates/rm_suc.html
{% extends 'base.html' %}

{% block title %}Login - My Website{% endblock %}

{% block content %}
<h1>     reminder settings succesfully Updated</h1>
    <H2>An email has been sent to your inbox, remember to <br>
        check your mail to suit your reminders for the child, Thank you</H2></p>
<br>
<form method="get" action="{% url 'home' %}">
    <button type="submit" class="btn btn-primary">dashboard</button>
  </form><br>
  <form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Logout</button>
{% endblock %}